### ISSUE TITLE
Export Binder 

### ISSUE THREAD

**Issue by SixExtreme** [ivankorobkov/python-inject#27]
export Binder in .pyi
```
T = typing.TypeVar('T')
Binder = typing.TypeVar('Binder')
Injector = typing.TypeVar('Injector')
```
if we use type-hint in project,
```
def my_config(binder: Binder):
    binder.bind(Config, load_config_file())
```

**Comment by ivankorobkov** [comment]
Hi! I saw your PR, but you have closed it already. Should this issue be also closed?

**Comment by SixExtreme** [comment]
> Hi! I saw your PR, but you have closed it already. Should this issue be also closed?
I'm sorry! I want to complete it in this weekend, last commit can not solve problem. We should export Injector and Binder in inject.pyi.

**Comment by ivankorobkov** [comment]
👍

**Comment by ivankorobkov** [comment]
Done in 3.5.1.
