### ISSUE TITLE
No ascii char in README.md  result in install error 

### ISSUE THREAD

**Issue by heyhpython** [ivankorobkov/python-inject#30]
there are no ascii encode chars in the readme.md , so when pip install inject on ascii encode platform there will be an error , I solve this by change the encoding to utf-8 in setup.py, but this error maybe confusing, hope to fix it.

**Comment by ivankorobkov** [comment]
Hi! Please, make a pull request if you need this to be fixed. Thanks.

**Comment by ivankorobkov** [comment]
Fixed in 3.5.2.
