### ISSUE TITLE
Type-hints are separated from implementation

### ISSUE THREAD

**Issue by andrewborba10** [ivankorobkov/python-inject#31]
Type-hints are separated into a .pyi file alongside inject.py. This seems unnecessary when they can be bundled together for easier integration. Right now, my IDE doesn't understand the type-hints by default, and while I'm sure I can fiddle with settings and get it to pick up the .pyi file (which is something I've had trouble with in the past) its just a hassle that gets passed on to every new consumer of this library.

I believe .pyi files were introduced as a stop-gap for the Python standard library to allow for incremental additions from the community and generally should be avoided in scenarios like this where the implementation can be fairly easily updated.

I would gladly volunteer to do the work on this (in fact, I already wrote some type-hints within our own project via a shim between our code and this library, but that approach has some short-falls that ultimately motivated me to come here).

Please let me know if you're on board with this idea and I can submit a pull request.

**Comment by andrewborba10** [comment]
I'm done with the changes, let me know how you would want to integrate them! I can push a new branch and to this repo if you give me write permission and then I can submit a pull request. Thanks!

While I did the typing annotations in a Python 2-compatible way, it will still require the typing module to be available on the module path. Hopefully this is ok.

**Comment by ivankorobkov** [comment]
Hi, can it break Python2 compatibility somehow? If not, please make a pull request.

**Comment by andrewborba10** [comment]
This change shouldn't break Python 2 compatibility. Can you give me permission to push to a new branch here? Or did you just want me to fork the whole repo?

**Comment by ivankorobkov** [comment]
I have merged your pull request. Thanks. Please, close the issue if it's done.

**Comment by ivankorobkov** [comment]
Should I release a patch version?

**Comment by andrewborba10** [comment]
Sure, that would be great, thanks!
