### ISSUE TITLE
Type hints are not compatible with mypy

### ISSUE THREAD

**Issue by ajgrover** [ivankorobkov/python-inject#36]
Hello - I'm running into an issue where running `mypy` on a project that uses `inject` gives the following error on every import:

```
path/to/file.py:1: error: Cannot find module named 'inject'
...
```

Based on the [mypy docs](https://mypy.readthedocs.io/en/latest/installed_packages.html) it appears that a `py.typed` file is necessary for PEP 561 compatibility. I tried adding this file and installing my fork but I wasn't able to get it working in the time I had. I'm not an expert with setuptools by any means so maybe [my simple change](https://github.com/ajgrover/python-inject/commit/cc8b2f903030c42e04cc43551a5c4af02ccd68ce) based on the mypy docs was not correct.

If it matters, I am using Python 3.7.4 and my project is using `pipenv`. There are no issues with mypy and any other third party libs.

Any help would be appreciated!

cc @andrewborba10, not sure if you are using `mypy` in your workflow

**Comment by ivankorobkov** [comment]
Hi!

If I get it right, there should be an empty `py.typed` file at the root of the repository. If that's all that should be done, then please make a pull-request.

**Comment by ivankorobkov** [comment]
I have released a new version with your fixes https://pypi.org/project/Inject/3.5.4/
