### ISSUE TITLE
Better type dependency injection

### ISSUE THREAD

**Issue by wisepotato** [ivankorobkov/python-inject#42]
Hi, great package. Im currently using the latest version `3.5.4` and I currently have to 'cast' my injected instances, is there a possibility of making this typed? (I might introduce a PR, but just wanted to check with you)

so instead of:
```python
config: Configuration = inject.get_instance(Configuration)
```
I would just get
```
config = inject.get_instance(Configuration)
```

**Comment by wisepotato** [comment]
Even passing  type generic would be fine by me as in `inject.get_instance(Configuration, T=Configuration)`

**Comment by ivankorobkov** [comment]
Hi,

Thanks. Sure, make a PR and I'll release the next version.

I like the first way:
```python
config = inject.get_instance(Configuration)
```

**Comment by wisepotato** [comment]
Problem is, if we want that, I will need to change the `get_instance` method to:

```python
    def get_instance(self, cls : T) -> T:
```
which, afaik breaks compatibility with python < 3.5

**Comment by ivankorobkov** [comment]
I think v4 just for 3.5+ is OK.

**Comment by wisepotato** [comment]
Cool!

**Comment by ivankorobkov** [comment]
Thank you for your contribution. Release 4.0.0 is out. You can get it from the pypi https://pypi.org/project/Inject/
