### ISSUE TITLE
Type hints mismatch?

### ISSUE THREAD

**Issue by 45deg** [ivankorobkov/python-inject#45]
Hello,
I caught a type error with IntelliJ IDE caused by the inferred type of `inject.attr(IFoo)` is not `IFoo` but `Type[IFoo]`. Inspecting the library, I found the two different annotation of type:
```python
def attr(cls: T) -> T:
    # type: (Binding) -> T
    """Return a attribute injection (descriptor)."""
    return _AttributeInjection(cls)
```
After changing `cls: T` with `cls: Binding`, the inference goes right.

Is there any reason for these different annotations (backward compatibility, etc.)? 
I should have made a PR for that if it is an unintentional mistake but asked at first for clarification.

Thanks for your works.

**Comment by ivankorobkov** [comment]
Hi,

I think it's a typo. Please, make a PR and I'll make a new release.

**Comment by 45deg** [comment]
Thanks, I'll prepare for PR.
