### ISSUE TITLE
pip install fails on windowsOS

### ISSUE THREAD

**Issue by sonedaiki** [ivankorobkov/python-inject#48]
Hello
I get the following error when I pip install on windows.

>UnicodeDecodeError: 'cp932' codec can't decode byte 0x93 in position 471: illegal multibyte sequence

Perhaps modifying setup.py(line7~9) as follows will cure it?

```
def read_description():
    with open('README.md', 'r', encoding='utf-8') as f:
        return f.read()
```
or
```
def read_description():
    with open('README.md', 'r', encoding='utf-8_sig') as f:
        return f.read()
```
Thanks for your works.

**Comment by ivankorobkov** [comment]
Done.

https://pypi.org/project/Inject/4.1.1/
