### ISSUE TITLE
[Question] Positional injection?

### ISSUE THREAD

**Issue by ancostas** [ivankorobkov/python-inject#51]
Hello, I really like your package!

I'm wondering about something in your docs, they say that: `inject.params injects dependencies as keyword arguments or positional argument.`, but it seems that they only get injected as keyword arguments?

```
def injection_wrapper(*args: Any, **kwargs: Any) -> T:
    # Assumes whatever is provided fulfills type constraints
    provided_params = frozenset(arg_names[:len(args)]) | frozenset(kwargs.keys())
    # Injects whatever is missing into kwargs
    for param, cls in params_to_provide.items():
        if param not in provided_params:
            kwargs[param] = instance(cls)
    return func(*args, **kwargs)
```

For example, the following works:
```
class Provider:
    def __init__(self, num: int):
        self._num = num

    def provide(self):
        return self._num

@inject.params(a=Provider)
def test_func(a: Provider, b: int = 100):
    return a.provide() + b

inject.configure(lambda binder: binder.bind(Provider, Provider(123)))

assert test_func() == 223
assert test_func(b=200) == 323
```

but this doesn't:
`assert test_func(200) == 323 # AttributeError: 'int' object has no attribute 'provide'`

I've been playing with the code a bit, and have something that would satisfy the above tests (and your existing tests). Would you be interested in taking a look/is this something you think makes sense for this library?

For context: 
I work with projects that have many signatures a la `func(dep_1: A, dep_2: B, arg_1, arg_2)` and would love to use your library to inject them and invoke with `func(arg_1, arg_2)` without needing to refactor the code base much. 

Currently, it seems like I'd need to make them all this: `func(arg_1, arg_2, dep_1: A, dep_2: B)`

**Comment by ivankorobkov** [comment]
Hi!

> inject.params injects dependencies as keyword arguments or positional argument., but it seems that they only get injected as keyword arguments?
It means that injected dependencies can be specified both as positional or keyword arguments. For example, take a look at `a`:
```python
def test_func(a: Provider, b: int = 100):
def test_func(a: Provider = 0, b: int = 100):
```

You get an error here:
```python
assert test_func(200) == 323 # AttributeError: 'int' object has no attribute 'provide'
```
Because you pass `200` as a positional argument `a`. So `a` is not injected. However, later you call `a.provide()` on it. `int` does not have such a method.

> I work with projects that have many signatures a la `func(dep_1: A, dep_2: B, arg_1, arg_2)`
All arguments here are positional. It means that the first arg you pass to `func` is always `dep_1`. 

If you want to call the func as `func(arg_1, arg_2)` you either need to change the args order as you already wrote:
```python
func(arg_1, arg_2, dep_1: A, dep_2: B)
```

Or make deps keyword arguments:
```python
func(arg_1, arg_2, dep_1: A = None, dep_2: B = None)
```

**Comment by ancostas** [comment]
Yup, makes sense!

I guess what I'm wondering is if it would make sense to have an implementation such that `params` and `autoparams` produce a partial function that takes configured dependencies from `inject` regardless of their order in the original function's signature.

In my mind this would be a benefit since it allows the code being injected to be agnostic of `inject` altogether. 

This seems like it would be especially helpful when injecting things from libraries not controlled by the consuming project. On the other hand, I suppose the consuming project could set up these partial functions itself.

**Comment by ivankorobkov** [comment]
Even though I am not fond of function currying I think it makes sense here. However, `inject` has been around for quite some time and I think its core logic should be left intact.

You can write a specific utility function which wraps `inject.params/autoparams` and returns a partial function if you need. Take a look at https://github.com/ivankorobkov/python-inject/blob/master/inject/__init__.py#L255 and https://github.com/ivankorobkov/python-inject/blob/master/inject/__init__.py#L375

**Comment by ancostas** [comment]
Ok, sounds good to me -- this is pretty much what I did on my local branch. Thanks for taking the time :+1: !
