### ISSUE TITLE
How to inject dependencies that have dependencies

### ISSUE THREAD

**Issue by caiquecp** [ivankorobkov/python-inject#63]
What I'm trying to do:

```python
def config_inject(binder: inject.Binder) -> None:
        binder.bind(Database, MongoDatabase())
        binder.bind(SomeRepository, MongoSomeRepository())
    inject.configure(config_inject)
```

MongoSomeRepository has dependency over Database, but when I'm trying to config it this way I got the error "No injector is configured". I guess it happens because at the moment the bind is being made the injector is not ready. So how do I handle this case?

**Comment by ivankorobkov** [comment]
Hi,

Use ‘binder.bind_to_constructor(Database, MongoDatabase)’. 

‘MongoDatabase()’ inside ‘config_injector’ tries to get its dependencies and accesses the global injector which is not configured yet.

**Comment by caiquecp** [comment]
OK, I'll do it. Thank you!
