### ISSUE TITLE
inspect.iscoroutinefunction fails after inject wraps

### ISSUE THREAD

**Issue by nikordaris** [ivankorobkov/python-inject#67]
Decorating functions with param/params/autoparams returns a synchronous function instead of preserving the async function. The following inspect.iscoroutinefunction will fail. This causes problems when other decorators depend on inspecting the function prior to executing it. 

```python
@inject.param("val")
async def test_func(val):
    return val

assert inspect.iscoroutinefunction(test_func)
```

**Comment by nikordaris** [comment]
@ivankorobkov when do we expect to get a version cut with this fix?

**Comment by ivankorobkov** [comment]
Oh, I'm sorry. It just slipped my mind. 

The next version https://pypi.org/project/Inject/4.3.0/

**Comment by nikordaris** [comment]
No worries! Thanks!!
