### ISSUE TITLE
Can I use this with Python 3.10? Is this project still maintained?

### ISSUE THREAD

**Issue by svenwanzenried** [ivankorobkov/python-inject#87]

**Comment by ivankorobkov** [comment]
Hi,

I think, you can use it with Python 3.10. And the project is still maintained a little bit 🙂 Though it’s quite stable and requires almost zero maintenance.

**Comment by svenwanzenried** [comment]
Ok, thank you very much! It seems to be a very useful module! I'll definetly try it out :)
