### ISSUE TITLE
Version 5.0.0 unintentially installs "typeshed" package, breaking VS code / pylance / pyright

### ISSUE THREAD

**Issue by caspervdw** [ivankorobkov/python-inject#89]
See https://github.com/microsoft/pyright/issues/5611 for the discussion at pyright.

The new version of pyright will deal with this, but it is for sure something to be fixed here.

**Comment by ivankorobkov** [comment]
Hi!

OK, I see. I will try to fix it in a couple of days and release the next version.

Thank you for reporting a bug.

**Comment by ivankorobkov** [comment]
Fixed in https://pypi.org/project/inject/5.1.0/
