### ISSUE TITLE
Syntax error in inject 5.2.0

### ISSUE THREAD

**Issue by mayesca** [ivankorobkov/python-inject#93]
Hi, when upgrading to inject v5.2.0 I'm encountering the following error which comes from this [line](https://github.com/ivankorobkov/python-inject/blob/122c55186eaf7a28f195bfb075c350e292fd4417/src/inject/__init__.py#L334)

```
lib/python3.8/site-packages/inject/__init__.py", line 334, in _ParametersInjection
    provided_params: frozenset[str],
TypeError: 'type' object is not subscriptable
```

Should the type hint here be using FrozenSet from the typing package?

**Comment by merwok** [comment]
This is valid, but not for Python 3.8

**Comment by mayesca** [comment]
Oh 🤦 , thanks for the clarification.
